import { NextRequest } from "next/server";
import { labelPdf } from "@/lib/shippo-server";

/**
 * Commercial invoice — 8.5x11in PDF (612x792pt), the format Shippo returns
 * for international transactions (`commercial_invoice_url`). In mock mode we
 * generate it locally with the order facts; with a live Shippo key the real
 * transaction response carries Shippo's own invoice URL and this route is a
 * fallback for manual-carrier lanes (China Post, Yanwen) that Shippo doesn't
 * cover — which is exactly when a seller has to produce their own paperwork.
 */
export async function GET(req: NextRequest) {
  const p = req.nextUrl.searchParams;
  const ref = p.get("ref") ?? "—";
  const buyer = p.get("buyer") ?? "—";
  const addr = (p.get("addr") ?? "").split("|").filter(Boolean);
  const item = p.get("item") ?? "—";
  const qty = p.get("qty") ?? "1";
  const value = p.get("value") ?? "0.00";
  const tracking = p.get("tn") ?? "";
  const today = new Date().toISOString().slice(0, 10);

  const pdf = labelPdf(
    [
      "COMMERCIAL INVOICE",
      "================================================",
      `Invoice date   ${today}          Order  ${ref}`,
      tracking ? `Tracking       ${tracking}` : "",
      "",
      "EXPORTER / SELLER",
      "  SuLab (via Tindie)",
      "  2261 Market St, San Francisco CA 94114, US",
      "",
      "CONSIGNEE / BUYER",
      `  ${buyer}`,
      ...addr.map((l) => `  ${l}`),
      "",
      "GOODS",
      "  Description                      Qty    Unit(USD)   Total",
      `  ${item.slice(0, 32).padEnd(32)} ${qty.padStart(3)}    ${value.padStart(8)}   ${(
        parseFloat(value) * parseInt(qty || "1")
      ).toFixed(2).padStart(8)}`,
      "  HS code: 8543.70 (electronic modules)   Origin: US",
      "",
      "  Reason for export: SALE",
      "  Incoterm: DDU",
      "",
      "IOSS: VAT collected at checkout via marketplace IOSS",
      "registration - buyer owes nothing on delivery.",
      "",
      "I declare the information above is true and correct.",
      "",
      "  ____________________________",
      "  SuLab, " + today,
      "",
      "** PROTOTYPE DOCUMENT - generated by the mock endpoint **",
    ].filter((l) => l !== ""),
    { w: 612, h: 792, fontSize: 10 }
  );
  return new Response(Buffer.from(pdf), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `inline; filename="commercial_invoice_${ref}.pdf"`,
    },
  });
}
