import {
  ProductQuestion,
  VersionNote,
  SellerApplication,
  ProductSubmission,
  DigitalProduct,
  ServicePartner,
  QuoteRequest,
  ManufacturingOrder,
  Entitlement,
  PaymentConfig,
  Dispute,
  IpComplaint,
} from "./types";
import { Fulfillment } from "./shipping";

// Platform payment config — in production this comes from the admin panel / DB.
export const paymentConfig: PaymentConfig = {
  // Tindie's classic behaviour: the seller carries the processing cost. Made
  // explicit here rather than left as a gap in the ledger.
  feeAllocation: "seller_pays",
  taxRate: 0,
  servicePlatformFeePercent: 0.12,
  digitalMinimumWithoutFee: 10,
  smallOrderFee: 0.49,
  minimumDigitalPrice: 2,
  stripeFixedFee: 0.3,
  stripePercent: 0.029,
  platformFeePercent: 0.1,
  platformFeePercentPhysical: 0.05,
};

// ---------------------------------------------------------------------------
// Partners (data-driven — the routing engine reads this list, nothing hardcoded)
// ---------------------------------------------------------------------------
export const partners: ServicePartner[] = [
  {
    id: "pt_huaqiu",
    name: "Huaqiu (HQ)",
    slug: "huaqiu",
    logoToken: "from-orange-400 to-red-500",
    description:
      "PCB fabrication, SMT assembly, component sourcing, stencils and DFM checks. Serves overseas Tindie designs from China with global shipping.",
    partnerTypes: ["pcb_manufacturer", "pcb_assembly", "component_sourcing", "testing_service"],
    headquartersCountry: "CN",
    serviceCountries: ["GLOBAL"],
    shippingCountries: ["GLOBAL"],
    languages: ["English", "Chinese"],
    minLeadDays: 5,
    maxLeadDays: 12,
    fromPricePcb: 8,
    fromPriceAssembly: 42,
    quoteMode: "manual_quote",
    commissionModel: "referral",
    commissionRate: 0.05,
    rating: 4.7,
    completedOrders: 1284,
    disputeRate: 0.012,
    onTimeRate: 0.96,
    // Hard capability limits — used to EXCLUDE, never to score.
    maxLayers: 16,
    materials: ["FR-4", "Aluminium", "Rogers", "Flex"],
    minTraceMm: 0.075,
    minQty: 5,
    maxQty: 100000,
    currencies: ["USD", "CNY", "EUR"],
    packages: ["THT", "0402", "0201", "QFN", "BGA"],
    // Operational readiness — all of it must hold before a buyer sees them.
    contractStatus: "signed",
    ndaStatus: "signed",
    dataProcessingAgreement: "signed",
    payoutReady: true,
    apiHealth: "healthy",
    acceptingNewOrders: true,
    capacityStatus: "normal",
    lastCapabilityVerifiedAt: "2026-06-28",
    status: "active",
    featured: true,
    strategic: true,
  },
  {
    id: "pt_kicadsvc",
    name: "KiCad Design Services",
    slug: "kicad-design-services",
    logoToken: "from-sky-400 to-blue-600",
    description:
      "Professional KiCad-ecosystem engineering: design review, engineering fixes, KiCad migration, advanced PCB design, training and Verified Design support.",
    partnerTypes: ["design_service", "design_review", "certification_service"],
    headquartersCountry: "US",
    serviceCountries: ["GLOBAL"],
    shippingCountries: [],
    languages: ["English"],
    minLeadDays: 1,
    maxLeadDays: 2,
    quoteMode: "manual_quote",
    commissionModel: "percentage",
    commissionRate: 0.1,
    rating: 4.9,
    completedOrders: 342,
    disputeRate: 0.006,
    onTimeRate: 0.98,
    // Hard capability limits — used to EXCLUDE, never to score.
    maxLayers: 99,
    materials: ["FR-4", "Rogers", "Aluminium", "Flex"],
    minTraceMm: 0.05,
    minQty: 1,
    maxQty: 1000000,
    currencies: ["USD", "EUR"],
    packages: ["THT", "0402", "0201", "QFN", "BGA"],
    // Operational readiness — all of it must hold before a buyer sees them.
    contractStatus: "signed",
    ndaStatus: "signed",
    dataProcessingAgreement: "signed",
    payoutReady: true,
    apiHealth: "healthy",
    acceptingNewOrders: true,
    capacityStatus: "normal",
    lastCapabilityVerifiedAt: "2026-07-02",
    status: "active",
    featured: true,
    strategic: true,
  },
  {
    id: "pt_eu_pcb",
    name: "EuroCircuits Local (preview)",
    slug: "eu-pcb-preview",
    logoToken: "from-emerald-400 to-teal-600",
    description:
      "EU-local PCB & PCBA with tax-friendly invoicing, CE-related services and regional warehousing. Onboarding — shown as a future routing option.",
    partnerTypes: ["pcb_manufacturer", "pcb_assembly", "warehousing"],
    headquartersCountry: "DE",
    serviceCountries: ["DE", "FR", "NL", "IT", "ES", "SE"],
    shippingCountries: ["DE", "FR", "NL", "IT", "ES", "SE", "GB"],
    languages: ["English", "Deutsch"],
    minLeadDays: 4,
    maxLeadDays: 9,
    fromPricePcb: 14,
    fromPriceAssembly: 58,
    quoteMode: "email_request",
    commissionModel: "referral",
    commissionRate: 0.05,
    rating: 4.6,
    completedOrders: 87,
    disputeRate: 0.02,
    onTimeRate: 0.93,
    // Hard capability limits — used to EXCLUDE, never to score.
    maxLayers: 8,
    materials: ["FR-4"],
    minTraceMm: 0.1,
    minQty: 5,
    maxQty: 5000,
    currencies: ["EUR", "USD"],
    packages: ["THT", "0402", "QFN"],
    // Operational readiness — all of it must hold before a buyer sees them.
    contractStatus: "negotiating",
    ndaStatus: "signed",
    dataProcessingAgreement: "none",
    payoutReady: false,
    apiHealth: "not_integrated",
    acceptingNewOrders: true,
    capacityStatus: "normal",
    lastCapabilityVerifiedAt: "2026-05-20",
    status: "draft",
    featured: false,
    strategic: false,
  },
  {
    id: "pt_us_pcba",
    name: "US Quickturn PCBA (preview)",
    slug: "us-pcba-preview",
    logoToken: "from-indigo-400 to-purple-600",
    description:
      "US-local PCB and PCBA, fast turnaround, local engineering support, small-batch assembly, domestic warehousing and after-sales.",
    partnerTypes: ["testing_service", "warehousing", "fulfillment", "local_support"],
    headquartersCountry: "US",
    serviceCountries: ["US", "CA"],
    shippingCountries: ["US", "CA"],
    languages: ["English"],
    minLeadDays: 3,
    maxLeadDays: 7,
    fromPricePcb: 19,
    fromPriceAssembly: 75,
    quoteMode: "email_request",
    commissionModel: "referral",
    commissionRate: 0.05,
    rating: 4.5,
    completedOrders: 54,
    disputeRate: 0.03,
    onTimeRate: 0.91,
    // Hard capability limits — used to EXCLUDE, never to score.
    maxLayers: 12,
    materials: ["FR-4", "Rogers"],
    minTraceMm: 0.09,
    minQty: 1,
    maxQty: 2000,
    currencies: ["USD"],
    packages: ["THT", "0402", "0201", "QFN", "BGA"],
    // Operational readiness — all of it must hold before a buyer sees them.
    contractStatus: "signed",
    ndaStatus: "signed",
    dataProcessingAgreement: "signed",
    payoutReady: true,
    apiHealth: "healthy",
    acceptingNewOrders: true,
    capacityStatus: "constrained",
    lastCapabilityVerifiedAt: "2026-07-05",
    status: "active",
    featured: false,
    strategic: false,
  },
];

// ---------------------------------------------------------------------------
// Digital products (3 complete examples per the brief)
// ---------------------------------------------------------------------------
export const products: DigitalProduct[] = [
  {
    id: "dp_rp2350",
    slug: "rp2350-pocket-instrument",
    productType: "digital",
    title: "RP2350 Multi-function Pocket Instrument",
    tagline:
      "A pocket-sized bench tool — logic probe, signal generator and voltmeter — built around the RP2350 on a compact 4-layer board.",
    category: "kicad_full_project",
    sellerId: "sel_gongyu",
    sellerName: "SuLab",
    sellerCountry: "US",
    kicadVersion: "KiCad 9",
    verifyLevel: 3,
    verifiedVersion: "1.2.0",
    reviewPartner: "KiCad Design Services",
    downloads: 214,
    timesManufactured: 27,
    updatedAt: "2026-07-02",
    layers: 4,
    sizeMm: "58 × 34 mm",
    heroThumb: "from-slate-700 to-slate-900",
    makeEnabled: true,
    allowFullFileToPartner: false,
    rating: 4.8,
    reviewCount: 19,
    supportResponse: "~4 hours",
    licenses: [
      {
        id: "lic_p_1",
        kind: "personal",
        name: "Personal License",
        price: 5,
        blurb: "For personal projects and learning. Build for yourself, no resale.",
        unitLimit: 0,
        updatePolicy: "minor_updates",
        manufacturingRights: { personalUnits: 5, commercialUnits: 0, partnerManufacturingAllowed: true, sourceFilesIncluded: false },
      },
      {
        id: "lic_c_1",
        kind: "commercial_limited",
        name: "Commercial License — up to 100 units",
        price: 39,
        blurb: "Sell up to 100 physical products built from this design.",
        unitLimit: 100,
        updatePolicy: "all_updates_for_period",
        manufacturingRights: { personalUnits: 100, commercialUnits: 100, partnerManufacturingAllowed: true, sourceFilesIncluded: false },
      },
      {
        id: "lic_u_1",
        kind: "unlimited_commercial",
        name: "Unlimited Commercial License",
        price: 99,
        blurb: "Unlimited physical production. No unit cap.",
        unitLimit: null,
        updatePolicy: "lifetime_updates",
        manufacturingRights: { personalUnits: 1000000, commercialUnits: 1000000, partnerManufacturingAllowed: true, sourceFilesIncluded: true },
      },
    ],
    bom: [
      { refdes: "U1", mpn: "RP2350A", manufacturer: "Raspberry Pi", value: "MCU", package: "QFN-60", qty: 1, confidence: 0.99 },
      { refdes: "U2", mpn: "W25Q128JVSIQ", manufacturer: "Winbond", value: "16MB Flash", package: "SOIC-8", qty: 1, confidence: 0.97 },
      { refdes: "U3", mpn: "TPS63020", manufacturer: "TI", value: "Buck-Boost", package: "VSON-10", qty: 1, confidence: 0.94 },
      { refdes: "J1", mpn: "USB4110-GF-A", manufacturer: "GCT", value: "USB-C", package: "SMD", qty: 1, confidence: 0.88, needsReview: true },
      { refdes: "D1", mpn: "PESD5V0X1BT", manufacturer: "Nexperia", value: "TVS", package: "SOD-523", qty: 4, confidence: 0.72, needsReview: true },
      { refdes: "C1-C12", mpn: "CL10B104KB8NNNC", manufacturer: "Samsung", value: "100nF", package: "0402", qty: 12, confidence: 0.99 },
    ],
    files: [
      { path: "rp2350-instrument.kicad_pro", type: "KiCad Project", sizeKb: 12, sha256: "9f2a…c71b" },
      { path: "rp2350-instrument.kicad_sch", type: "Schematic", sizeKb: 486, sha256: "1c4d…88af" },
      { path: "rp2350-instrument.kicad_pcb", type: "PCB Layout", sizeKb: 902, sha256: "77b0…2e19" },
      { path: "gerbers/", type: "Gerber package", sizeKb: 240, sha256: "a3e8…40dd" },
      { path: "bom.csv", type: "BOM", sizeKb: 8, sha256: "5511…9cae" },
      { path: "firmware/", type: "Firmware source", sizeKb: 1340, sha256: "be21…7f03" },
      { path: "enclosure.step", type: "STEP model", sizeKb: 3100, sha256: "0d9c…11a7" },
    ],
  },
  {
    id: "dp_rflib",
    slug: "rf-symbols-footprints-pack",
    productType: "digital",
    title: "High-quality RF Symbols & Footprints Pack",
    tagline:
      "A carefully drawn library of RF connectors, filters and IC footprints with matched 3D models. Verified against KiCad 8 and 9.",
    category: "symbol_library",
    sellerId: "sel_rfhouse",
    sellerName: "RF House",
    sellerCountry: "DE",
    kicadVersion: "KiCad 8 / 9",
    verifyLevel: 1,
    downloads: 631,
    timesManufactured: 0,
    updatedAt: "2026-06-18",
    layers: 0,
    sizeMm: "—",
    heroThumb: "from-emerald-700 to-teal-900",
    makeEnabled: false,
    allowFullFileToPartner: false,
    rating: 4.9,
    reviewCount: 42,
    supportResponse: "~1 day",
    licenses: [
      {
        id: "lic_lib",
        kind: "personal",
        name: "Standard License",
        price: 12,
        blurb: "Use in unlimited personal and commercial KiCad projects. No redistribution of the library itself.",
        unitLimit: null,
        updatePolicy: "lifetime_updates",
        manufacturingRights: { personalUnits: 5, commercialUnits: 0, partnerManufacturingAllowed: true, sourceFilesIncluded: false },
      },
    ],
    bom: [],
    files: [
      { path: "rf.kicad_sym", type: "Symbol library", sizeKb: 210, sha256: "aa10…4c22" },
      { path: "rf.pretty/", type: "Footprint library", sizeKb: 640, sha256: "cd77…9901" },
      { path: "3d/", type: "3D models", sizeKb: 8800, sha256: "12ef…7ab5" },
    ],
  },
  {
    id: "dp_review",
    slug: "professional-kicad-design-review",
    productType: "digital",
    title: "Professional KiCad Design Review",
    tagline:
      "A senior engineer reviews your schematic and PCB for manufacturability, signal integrity basics, and file organization — with a written report.",
    category: "reference_design",
    sellerId: "pt_kicadsvc",
    sellerName: "KiCad Design Services",
    sellerCountry: "US",
    kicadVersion: "KiCad 7 / 8 / 9",
    verifyLevel: 0,
    downloads: 0,
    timesManufactured: 0,
    updatedAt: "2026-07-05",
    layers: 0,
    sizeMm: "—",
    heroThumb: "from-sky-700 to-blue-900",
    makeEnabled: false,
    allowFullFileToPartner: true,
    rating: 5.0,
    reviewCount: 11,
    supportResponse: "~1–2 business days",
    licenses: [
      {
        id: "lic_rev",
        kind: "custom",
        name: "Design Review — Standard",
        price: 99,
        blurb: "One round of review on a board up to 6 layers, with a written report and a follow-up call.",
        unitLimit: null,
        updatePolicy: "current_version_only",
        manufacturingRights: { personalUnits: 0, commercialUnits: 0, partnerManufacturingAllowed: false, sourceFilesIncluded: false },
      },
    ],
    bom: [],
    files: [],
  },
  // -------------------------------------------------------------------------
  // PHYSICAL — an assembled unit. The buyer must SEE what the seller set in
  // the back office: price, live stock, weight, handling time, ship profile.
  // -------------------------------------------------------------------------
  {
    id: "dp_pocket_assembled",
    slug: "pocket-instrument-assembled",
    title: "Pocket Instrument — Assembled & Tested Unit",
    productType: "physical",
    price: 89.0,
    stock: 34,
    weightG: 620,
    dimensionsMm: "118 × 74 × 22",
    shipProfileId: "sp_kit",
    handlingDays: "2–4 days",
    tagline: "The RP2350 pocket instrument, built, flashed and tested — scope, logic analyzer and signal generator in your pocket.",
    category: "complete_design",
    sellerId: "s_sulab",
    sellerName: "SuLab",
    sellerCountry: "US",
    kicadVersion: "—",
    verifyLevel: 3,
    verifiedVersion: "1.0.0",
    reviewPartner: "KiCad Design Services",
    downloads: 0,
    timesManufactured: 212,
    updatedAt: "2026-07-10",
    layers: 4,
    sizeMm: "98 × 56",
    heroThumb: "from-teal-600 to-emerald-800",
    makeEnabled: false,
    allowFullFileToPartner: false,
    rating: 4.9,
    reviewCount: 87,
    supportResponse: "~24 hours",
    licenses: [],
    bom: [],
    files: [],
  },
  // -------------------------------------------------------------------------
  // BUNDLE — hardware + the design files that made it. One cart line each.
  // -------------------------------------------------------------------------
  {
    id: "dp_pocket_bundle",
    slug: "pocket-instrument-kit-plus-sources",
    title: "Pocket Instrument Kit + Design Files (Bundle)",
    productType: "bundle",
    price: 129.0,
    stock: 18,
    weightG: 640,
    dimensionsMm: "118 × 74 × 26",
    shipProfileId: "sp_kit",
    handlingDays: "2–4 days",
    tagline: "The solder-it-yourself kit AND the full KiCad sources with a commercial licence — build one, then make it yours.",
    category: "complete_design",
    sellerId: "s_sulab",
    sellerName: "SuLab",
    sellerCountry: "US",
    kicadVersion: "KiCad 8.0",
    verifyLevel: 3,
    verifiedVersion: "1.0.0",
    reviewPartner: "KiCad Design Services",
    downloads: 96,
    timesManufactured: 212,
    updatedAt: "2026-07-08",
    layers: 4,
    sizeMm: "98 × 56",
    heroThumb: "from-indigo-600 to-violet-900",
    makeEnabled: true,
    allowFullFileToPartner: false,
    rating: 4.8,
    reviewCount: 41,
    supportResponse: "~24 hours",
    licenses: [
      {
        id: "lic_bundle",
        kind: "commercial_limited",
        name: "Bundle Licence (kit + sources, 100 units)",
        price: 129,
        blurb: "Included with the kit: full KiCad sources, minor updates, and the right to build up to 100 commercial units.",
        unitLimit: 100,
        updatePolicy: "minor_updates",
        manufacturingRights: { personalUnits: 100, commercialUnits: 100, partnerManufacturingAllowed: true, sourceFilesIncluded: false },
      },
    ],
    bom: [
      { refdes: "U1", mpn: "RP2350A", manufacturer: "Raspberry Pi", value: "RP2350A", package: "QFN-60", qty: 1, confidence: 1 },
      { refdes: "U2", mpn: "W25Q128JVSIQ", manufacturer: "Winbond", value: "128Mbit QSPI", package: "SOIC-8", qty: 1, confidence: 1 },
      { refdes: "J1", mpn: "TYPE-C-31-M-12", manufacturer: "HRO", value: "USB-C 16P", package: "SMD", qty: 1, confidence: 0.97 },
    ],
    files: [],
  },
  // -------------------------------------------------------------------------
  // PREORDER — stock 0 on purpose; the campaign carries the commitment.
  // -------------------------------------------------------------------------
  {
    id: "dp_logic_preorder",
    slug: "pocket-logic-analyzer-preorder",
    title: "Pocket Logic Analyzer — Batch 2 (Preorder)",
    productType: "physical",
    price: 79.0,
    stock: 0,
    preorderCampaignSlug: "pocket-logic-analyzer",
    weightG: 380,
    dimensionsMm: "92 × 58 × 18",
    shipProfileId: "sp_kit",
    handlingDays: "ships when batch completes",
    tagline: "16-channel 100 MS/s logic analyzer. Batch 2 builds when 50 units are committed — 37 already are.",
    category: "complete_design",
    sellerId: "s_sulab",
    sellerName: "SuLab",
    sellerCountry: "US",
    kicadVersion: "—",
    verifyLevel: 2,
    verifiedVersion: "0.9.0",
    downloads: 0,
    timesManufactured: 50,
    updatedAt: "2026-07-12",
    layers: 4,
    sizeMm: "84 × 50",
    heroThumb: "from-amber-500 to-orange-800",
    makeEnabled: false,
    allowFullFileToPartner: false,
    rating: 4.7,
    reviewCount: 12,
    supportResponse: "~24 hours",
    licenses: [],
    bom: [],
    files: [],
  },
];

// ---------------------------------------------------------------------------
// Quotes, orders, disputes, IP, entitlements
// ---------------------------------------------------------------------------
export const seedQuotes: QuoteRequest[] = [
  {
    id: "qr_1001",
    buyerName: "Ava Chen",
    productId: "dp_rp2350",
    productTitle: "RP2350 Multi-function Pocket Instrument",
    requestedServices: ["pcb_manufacturer", "pcb_assembly"],
    quantity: 20,
    destinationCountry: "US",
    targetDate: "2026-08-15",
    notes: "ENIG finish preferred. Need assembled units for a workshop.",
    partnerId: "pt_huaqiu",
    partnerName: "Huaqiu (HQ)",
    status: "quoted",
    createdAt: "2026-07-08",
    quotedTotal: 612,
    leadTimeDays: 9,
  },
  {
    id: "qr_1002",
    buyerName: "Marco Rossi",
    productId: "dp_rp2350",
    productTitle: "RP2350 Multi-function Pocket Instrument",
    requestedServices: ["design_review"],
    quantity: 1,
    destinationCountry: "IT",
    partnerId: "pt_kicadsvc",
    partnerName: "KiCad Design Services",
    status: "submitted",
    createdAt: "2026-07-10",
  },
];

export const seedOrders: ManufacturingOrder[] = [
  {
    id: "mo_5001",
    productTitle: "RP2350 Multi-function Pocket Instrument",
    partnerName: "Huaqiu (HQ)",
    buyerName: "Ava Chen",
    quantity: 20,
    total: 612,
    status: "in_production",
    placedAt: "2026-07-09",
    timeline: [
      { status: "awaiting_files", at: "2026-07-09", note: "Order placed, secure file link issued to partner." },
      { status: "in_review", at: "2026-07-09", note: "DFM check passed with 2 minor notes." },
      { status: "in_production", at: "2026-07-10", note: "Panelization complete, boards in fabrication." },
    ],
  },
];

export const seedDisputes: Dispute[] = [
  {
    id: "ds_9001",
    productTitle: "RP2350 Multi-function Pocket Instrument",
    buyerName: "Jordan Lee",
    sellerName: "SuLab",
    type: "missing_files",
    status: "seller_response",
    openedAt: "2026-07-11",
    messages: [
      { from: "buyer", at: "2026-07-11 09:12", body: "The STEP enclosure file referenced in the docs isn't in my download." },
      { from: "seller", at: "2026-07-11 14:40", body: "Apologies — the STEP was in a sub-folder that got excluded. Uploading a corrected v1.2.1 now." },
    ],
  },
];

export const seedIpComplaints: IpComplaint[] = [
  {
    id: "ip_7001",
    productTitle: "Generic USB-PD Trigger Board",
    complainant: "Acme Power Ltd.",
    rightsHolder: "Acme Power Ltd.",
    basis: "Alleged copy of a registered board layout.",
    status: "under_review",
    filedAt: "2026-07-06",
  },
];

export const seedEntitlements: Entitlement[] = [
  {
    id: "ent_3002",
    productId: "dp_pocket_bundle",
    productTitle: "Pocket Instrument Kit + Design Files (Bundle)",
    licenseName: "Personal License",
    grantedAt: "2026-07-08",
    downloadLimit: 10,
    downloadCount: 2,
    status: "active",
    purchasedVersionId: "av_bundle_100",
    latestAccessibleVersionId: "av_bundle_100",
    updatePolicy: "minor_updates",
    rights: {
      personalUnits: 5,
      commercialUnits: 0,
      partnerManufacturingAllowed: false,
      sourceFilesIncluded: true,
    },
    commercialUnitsUsed: 0,
    seats: 1,
    licenseSnapshotHash: "sha256:2b7e…91cc",
    termsAcceptedAt: "2026-07-08T14:03:11Z",
  },
  {
    id: "ent_3001",
    productId: "dp_rp2350",
    productTitle: "RP2350 Multi-function Pocket Instrument",
    licenseName: "Commercial License (100 units)",
    grantedAt: "2026-06-20",
    downloadLimit: 10,
    downloadCount: 8,
    status: "active",
    purchasedVersionId: "av_rp2350_100",
    latestAccessibleVersionId: "av_rp2350_100",
    updatePolicy: "minor_updates",
    rights: {
      personalUnits: 100,
      commercialUnits: 100,
      partnerManufacturingAllowed: true,
      sourceFilesIncluded: false,
    },
    commercialUnitsUsed: 40,
    seats: 1,
    licenseSnapshotHash: "sha256:9f2c…d41a",
    termsAcceptedAt: "2026-06-20T09:12:04Z",
  },
];

export const seedFulfillments: Fulfillment[] = [
  {
    id: "ff_5001",
    orderRef: "TD-88213",
    productTitle: "RS485 ↔ TTL Module (MAX485E) — assembled board",
    buyerName: "Lena Fischer",
    address: ["Lena Fischer", "Torstraße 140", "10119 Berlin", "Germany"],
    destination: "DE",
    weightG: 42,
    goodsValue: 19.99,
    qty: 2,
    sku: "RS485-TTL-A",
    status: "unfulfilled",
    placedAt: "2026-07-11",
  },
  {
    id: "ff_5002",
    orderRef: "TD-88207",
    productTitle: "RP2350 Pocket Instrument — kit",
    buyerName: "Marcus Webb",
    address: ["Marcus Webb", "2119 Bryant St, Apt 4", "San Francisco, CA 94110", "United States"],
    destination: "US",
    weightG: 180,
    goodsValue: 64.0,
    status: "label_purchased",
    carrierId: "usps",
    service: "USPS Priority",
    tracking: "9400 1000 0000 4471028836",
    labelCost: 9.4,
    placedAt: "2026-07-09",
  },
  {
    id: "ff_5003",
    orderRef: "TD-88190",
    productTitle: "RF Symbols Pack — printed reference card",
    buyerName: "Sofia Álvarez",
    address: ["Sofia Álvarez", "12 Corrimal St", "Wollongong NSW 2500", "Australia"],
    destination: "AU",
    weightG: 60,
    goodsValue: 12.0,
    status: "shipped",
    carrierId: "dhl_express",
    service: "DHL Express",
    tracking: "JD014600009212345678",
    labelCost: 36.5,
    placedAt: "2026-07-05",
  },
  {
    id: "ff_5004",
    orderRef: "TD-88231",
    productTitle: "RP2350 Pocket Instrument — assembled",
    buyerName: "Tomasz Kowalski",
    address: ["Tomasz Kowalski", "ul. Mokotowska 8/12", "00-641 Warszawa", "Poland"],
    destination: "DE",
    weightG: 165,
    goodsValue: 89.0,
    qty: 1,
    sku: "PKT-INST-ASM",
    status: "unfulfilled",
    placedAt: "2026-07-13",
  },
  {
    id: "ff_5005",
    orderRef: "TD-88235",
    productTitle: "RS485 ↔ TTL Module (MAX485E) — assembled board",
    buyerName: "Aiko Tanaka",
    address: ["Aiko Tanaka", "2-11-3 Meguro, Meguro-ku", "Tokyo 153-0063", "Japan"],
    destination: "JP",
    weightG: 84,
    goodsValue: 39.98,
    qty: 4,
    sku: "RS485-TTL-A",
    status: "unfulfilled",
    placedAt: "2026-07-14",
  },
];

export function getProduct(slug: string) {
  return products.find((p) => p.slug === slug);
}


// ---------------------------------------------------------------------------
// Q&A — a listing is alive after publish: buyers ask, the seller answers.
// ---------------------------------------------------------------------------
export const seedQuestions: ProductQuestion[] = [
  {
    id: "q_1",
    productId: "dp_pocket_assembled",
    askedBy: "mkr_jensen",
    askedAt: "2026-07-11",
    question: "Does the assembled unit ship with the acrylic case installed, or do I need to assemble that part?",
    answer: "Fully assembled including the case — you only peel the protective film. Firmware is flashed and each unit runs a 12-point functional test before packing.",
    answeredAt: "2026-07-11",
  },
  {
    id: "q_2",
    productId: "dp_pocket_bundle",
    askedBy: "hw_elena",
    askedAt: "2026-07-12",
    question: "If I buy the bundle, do future minor versions of the design files come included?",
    answer: "Yes — the bundle licence includes minor updates (1.x). A 2.0 would be a paid upgrade, announced in the version notes first.",
    answeredAt: "2026-07-13",
  },
  {
    id: "q_3",
    productId: "dp_pocket_assembled",
    askedBy: "probe_master",
    askedAt: "2026-07-13",
    question: "What probe connector does it use — standard 2.54 mm header or something proprietary?",
  },
];

// Version notes posted AFTER publish — sellers keep the listing alive.
export const seedVersionNotes: VersionNote[] = [
  {
    id: "vn_1",
    productId: "dp_rp2350",
    semver: "1.1.0",
    note: "USB-C CC resistors corrected (5.1 kΩ), silkscreen cleanup, new STEP models for the case. v1.0 buyers on minor-updates policy get this free.",
    postedAt: "2026-07-08",
  },
  {
    id: "vn_2",
    productId: "dp_pocket_assembled",
    semver: "1.0.1",
    note: "Batch 3 units ship with the improved rotary encoder (Bourns PEC11R). No electrical changes.",
    postedAt: "2026-07-10",
  },
];

// ---------------------------------------------------------------------------
// Admin queues — new sellers apply, products get reviewed before going live.
// ---------------------------------------------------------------------------
export const seedSellerApplications: SellerApplication[] = [
  {
    id: "app_1",
    storeName: "Nordlys Electronics",
    applicantName: "K. Haugen",
    country: "NO",
    productsPlanned: "LoRa environmental sensors, KiCad reference designs",
    corridor: "stripe",
    appliedAt: "2026-07-12",
    status: "pending",
  },
  {
    id: "app_2",
    storeName: "Weiguang Electronics (Shenzhen)",
    applicantName: "Chen Li",
    country: "CN",
    productsPlanned: "FPGA dev boards, assembled test jigs",
    corridor: "wise",
    appliedAt: "2026-07-13",
    status: "pending",
  },
  {
    id: "app_3",
    storeName: "Bidouille Labs",
    applicantName: "M. Fournier",
    country: "FR",
    productsPlanned: "Eurorack synth modules (kits + assembled)",
    corridor: "stripe",
    appliedAt: "2026-07-09",
    status: "approved",
  },
];

export const seedProductSubmissions: ProductSubmission[] = [
  {
    id: "sub_1",
    productTitle: "CAN-FD Sniffer Pro (assembled)",
    sellerName: "Bidouille Labs",
    productType: "physical",
    submittedAt: "2026-07-13",
    ipDeclared: true,
    filesOk: true,
    status: "pending",
  },
  {
    id: "sub_2",
    productTitle: "STM32H7 Camera Board — KiCad sources",
    sellerName: "Nordlys Electronics",
    productType: "digital",
    submittedAt: "2026-07-13",
    ipDeclared: true,
    filesOk: false,
    status: "pending",
  },
  {
    id: "sub_3",
    productTitle: "\"Arduino Nano Plus\" clone board",
    sellerName: "quickboards2026",
    productType: "physical",
    submittedAt: "2026-07-12",
    ipDeclared: false,
    filesOk: true,
    status: "pending",
  },
];
