import {
  DigitalProduct,
  ServicePartner,
  QuoteRequest,
  ManufacturingOrder,
  Entitlement,
  PaymentConfig,
  Dispute,
  IpComplaint,
} from "./types";

// Platform payment config — in production this comes from the admin panel / DB.
export const paymentConfig: PaymentConfig = {
  digitalMinimumWithoutFee: 10,
  smallOrderFee: 0.49,
  minimumDigitalPrice: 2,
  stripeFixedFee: 0.3,
  stripePercent: 0.029,
  platformFeePercent: 0.1,
};

// ---------------------------------------------------------------------------
// Partners (data-driven — the routing engine reads this list, nothing hardcoded)
// ---------------------------------------------------------------------------
export const partners: ServicePartner[] = [
  {
    id: "pt_huaqiu",
    name: "Huaqiu (HQ)",
    slug: "huaqiu",
    logoToken: "from-orange-400 to-red-500",
    description:
      "PCB fabrication, SMT assembly, component sourcing, stencils and DFM checks. Serves overseas Tindie designs from China with global shipping.",
    partnerTypes: ["pcb_manufacturer", "pcb_assembly", "component_sourcing", "testing_service"],
    headquartersCountry: "CN",
    serviceCountries: ["GLOBAL"],
    shippingCountries: ["GLOBAL"],
    languages: ["English", "中文"],
    minLeadDays: 5,
    maxLeadDays: 12,
    fromPricePcb: 8,
    fromPriceAssembly: 42,
    quoteMode: "manual_quote",
    commissionModel: "referral",
    commissionRate: 0.05,
    rating: 4.7,
    completedOrders: 1284,
    disputeRate: 0.012,
    onTimeRate: 0.96,
    status: "active",
    featured: true,
    strategic: true,
  },
  {
    id: "pt_kicadsvc",
    name: "KiCad Design Services",
    slug: "kicad-design-services",
    logoToken: "from-sky-400 to-blue-600",
    description:
      "Professional KiCad-ecosystem engineering: design review, engineering fixes, KiCad migration, advanced PCB design, training and Verified Design support.",
    partnerTypes: ["design_service", "design_review", "certification_service"],
    headquartersCountry: "US",
    serviceCountries: ["GLOBAL"],
    shippingCountries: [],
    languages: ["English"],
    minLeadDays: 1,
    maxLeadDays: 2,
    quoteMode: "manual_quote",
    commissionModel: "percentage",
    commissionRate: 0.1,
    rating: 4.9,
    completedOrders: 342,
    disputeRate: 0.006,
    onTimeRate: 0.98,
    status: "active",
    featured: true,
    strategic: true,
  },
  {
    id: "pt_eu_pcb",
    name: "EuroCircuits Local (preview)",
    slug: "eu-pcb-preview",
    logoToken: "from-emerald-400 to-teal-600",
    description:
      "EU-local PCB & PCBA with tax-friendly invoicing, CE-related services and regional warehousing. Onboarding — shown as a future routing option.",
    partnerTypes: ["pcb_manufacturer", "pcb_assembly", "warehousing"],
    headquartersCountry: "DE",
    serviceCountries: ["DE", "FR", "NL", "IT", "ES", "SE"],
    shippingCountries: ["DE", "FR", "NL", "IT", "ES", "SE", "GB"],
    languages: ["English", "Deutsch"],
    minLeadDays: 4,
    maxLeadDays: 9,
    fromPricePcb: 14,
    fromPriceAssembly: 58,
    quoteMode: "email_request",
    commissionModel: "referral",
    commissionRate: 0.05,
    rating: 4.6,
    completedOrders: 87,
    disputeRate: 0.02,
    onTimeRate: 0.93,
    status: "draft",
    featured: false,
    strategic: false,
  },
  {
    id: "pt_us_pcba",
    name: "US Quickturn PCBA (preview)",
    slug: "us-pcba-preview",
    logoToken: "from-indigo-400 to-purple-600",
    description:
      "US-local PCB and PCBA, fast turnaround, local engineering support, small-batch assembly, domestic warehousing and after-sales.",
    partnerTypes: ["pcb_manufacturer", "pcb_assembly", "local_support", "fulfillment"],
    headquartersCountry: "US",
    serviceCountries: ["US", "CA"],
    shippingCountries: ["US", "CA"],
    languages: ["English"],
    minLeadDays: 3,
    maxLeadDays: 7,
    fromPricePcb: 19,
    fromPriceAssembly: 75,
    quoteMode: "email_request",
    commissionModel: "referral",
    commissionRate: 0.05,
    rating: 4.5,
    completedOrders: 54,
    disputeRate: 0.03,
    onTimeRate: 0.91,
    status: "draft",
    featured: false,
    strategic: false,
  },
];

// ---------------------------------------------------------------------------
// Digital products (3 complete examples per the brief)
// ---------------------------------------------------------------------------
export const products: DigitalProduct[] = [
  {
    id: "dp_rp2350",
    slug: "rp2350-pocket-instrument",
    title: "RP2350 Multi-function Pocket Instrument",
    tagline:
      "A pocket-sized bench tool — logic probe, signal generator and voltmeter — built around the RP2350 on a compact 4-layer board.",
    category: "kicad_full_project",
    sellerId: "sel_gongyu",
    sellerName: "SuLab",
    sellerCountry: "US",
    kicadVersion: "KiCad 9",
    verifyLevel: 3,
    verifiedVersion: "1.2.0",
    reviewPartner: "KiCad Design Services",
    downloads: 214,
    timesManufactured: 27,
    updatedAt: "2026-07-02",
    layers: 4,
    sizeMm: "58 × 34 mm",
    heroThumb: "from-slate-700 to-slate-900",
    makeEnabled: true,
    allowFullFileToPartner: false,
    rating: 4.8,
    reviewCount: 19,
    supportResponse: "~4 hours",
    licenses: [
      {
        id: "lic_p_1",
        kind: "personal",
        name: "Personal License",
        price: 5,
        blurb: "For personal projects and learning. Build for yourself, no resale.",
        unitLimit: 0,
        updatePolicy: "minor_updates",
      },
      {
        id: "lic_c_1",
        kind: "commercial_limited",
        name: "Commercial License — up to 100 units",
        price: 39,
        blurb: "Sell up to 100 physical products built from this design.",
        unitLimit: 100,
        updatePolicy: "all_updates_for_period",
      },
      {
        id: "lic_u_1",
        kind: "unlimited_commercial",
        name: "Unlimited Commercial License",
        price: 99,
        blurb: "Unlimited physical production. No unit cap.",
        unitLimit: null,
        updatePolicy: "lifetime_updates",
      },
    ],
    bom: [
      { refdes: "U1", mpn: "RP2350A", manufacturer: "Raspberry Pi", value: "MCU", package: "QFN-60", qty: 1, confidence: 0.99 },
      { refdes: "U2", mpn: "W25Q128JVSIQ", manufacturer: "Winbond", value: "16MB Flash", package: "SOIC-8", qty: 1, confidence: 0.97 },
      { refdes: "U3", mpn: "TPS63020", manufacturer: "TI", value: "Buck-Boost", package: "VSON-10", qty: 1, confidence: 0.94 },
      { refdes: "J1", mpn: "USB4110-GF-A", manufacturer: "GCT", value: "USB-C", package: "SMD", qty: 1, confidence: 0.88, needsReview: true },
      { refdes: "D1", mpn: "PESD5V0X1BT", manufacturer: "Nexperia", value: "TVS", package: "SOD-523", qty: 4, confidence: 0.72, needsReview: true },
      { refdes: "C1-C12", mpn: "CL10B104KB8NNNC", manufacturer: "Samsung", value: "100nF", package: "0402", qty: 12, confidence: 0.99 },
    ],
    files: [
      { path: "rp2350-instrument.kicad_pro", type: "KiCad Project", sizeKb: 12, sha256: "9f2a…c71b" },
      { path: "rp2350-instrument.kicad_sch", type: "Schematic", sizeKb: 486, sha256: "1c4d…88af" },
      { path: "rp2350-instrument.kicad_pcb", type: "PCB Layout", sizeKb: 902, sha256: "77b0…2e19" },
      { path: "gerbers/", type: "Gerber package", sizeKb: 240, sha256: "a3e8…40dd" },
      { path: "bom.csv", type: "BOM", sizeKb: 8, sha256: "5511…9cae" },
      { path: "firmware/", type: "Firmware source", sizeKb: 1340, sha256: "be21…7f03" },
      { path: "enclosure.step", type: "STEP model", sizeKb: 3100, sha256: "0d9c…11a7" },
    ],
  },
  {
    id: "dp_rflib",
    slug: "rf-symbols-footprints-pack",
    title: "High-quality RF Symbols & Footprints Pack",
    tagline:
      "A carefully drawn library of RF connectors, filters and IC footprints with matched 3D models. Verified against KiCad 8 and 9.",
    category: "symbol_library",
    sellerId: "sel_rfhouse",
    sellerName: "RF House",
    sellerCountry: "DE",
    kicadVersion: "KiCad 8 / 9",
    verifyLevel: 1,
    downloads: 631,
    timesManufactured: 0,
    updatedAt: "2026-06-18",
    layers: 0,
    sizeMm: "—",
    heroThumb: "from-emerald-700 to-teal-900",
    makeEnabled: false,
    allowFullFileToPartner: false,
    rating: 4.9,
    reviewCount: 42,
    supportResponse: "~1 day",
    licenses: [
      {
        id: "lic_lib",
        kind: "personal",
        name: "Standard License",
        price: 12,
        blurb: "Use in unlimited personal and commercial KiCad projects. No redistribution of the library itself.",
        unitLimit: null,
        updatePolicy: "lifetime_updates",
      },
    ],
    bom: [],
    files: [
      { path: "rf.kicad_sym", type: "Symbol library", sizeKb: 210, sha256: "aa10…4c22" },
      { path: "rf.pretty/", type: "Footprint library", sizeKb: 640, sha256: "cd77…9901" },
      { path: "3d/", type: "3D models", sizeKb: 8800, sha256: "12ef…7ab5" },
    ],
  },
  {
    id: "dp_review",
    slug: "professional-kicad-design-review",
    title: "Professional KiCad Design Review",
    tagline:
      "A senior engineer reviews your schematic and PCB for manufacturability, signal integrity basics, and file organization — with a written report.",
    category: "reference_design",
    sellerId: "pt_kicadsvc",
    sellerName: "KiCad Design Services",
    sellerCountry: "US",
    kicadVersion: "KiCad 7 / 8 / 9",
    verifyLevel: 0,
    downloads: 0,
    timesManufactured: 0,
    updatedAt: "2026-07-05",
    layers: 0,
    sizeMm: "—",
    heroThumb: "from-sky-700 to-blue-900",
    makeEnabled: false,
    allowFullFileToPartner: true,
    rating: 5.0,
    reviewCount: 11,
    supportResponse: "~1–2 business days",
    licenses: [
      {
        id: "lic_rev",
        kind: "custom",
        name: "Design Review — Standard",
        price: 99,
        blurb: "One round of review on a board up to 6 layers, with a written report and a follow-up call.",
        unitLimit: null,
        updatePolicy: "current_version_only",
      },
    ],
    bom: [],
    files: [],
  },
];

// ---------------------------------------------------------------------------
// Quotes, orders, disputes, IP, entitlements
// ---------------------------------------------------------------------------
export const seedQuotes: QuoteRequest[] = [
  {
    id: "qr_1001",
    buyerName: "Ava Chen",
    productId: "dp_rp2350",
    productTitle: "RP2350 Multi-function Pocket Instrument",
    requestedServices: ["pcb_manufacturer", "pcb_assembly"],
    quantity: 20,
    destinationCountry: "US",
    targetDate: "2026-08-15",
    notes: "ENIG finish preferred. Need assembled units for a workshop.",
    partnerId: "pt_huaqiu",
    partnerName: "Huaqiu (HQ)",
    status: "quoted",
    createdAt: "2026-07-08",
    quotedTotal: 612,
    leadTimeDays: 9,
  },
  {
    id: "qr_1002",
    buyerName: "Marco Rossi",
    productId: "dp_rp2350",
    productTitle: "RP2350 Multi-function Pocket Instrument",
    requestedServices: ["design_review"],
    quantity: 1,
    destinationCountry: "IT",
    partnerId: "pt_kicadsvc",
    partnerName: "KiCad Design Services",
    status: "submitted",
    createdAt: "2026-07-10",
  },
];

export const seedOrders: ManufacturingOrder[] = [
  {
    id: "mo_5001",
    productTitle: "RP2350 Multi-function Pocket Instrument",
    partnerName: "Huaqiu (HQ)",
    buyerName: "Ava Chen",
    quantity: 20,
    total: 612,
    status: "in_production",
    placedAt: "2026-07-09",
    timeline: [
      { status: "awaiting_files", at: "2026-07-09", note: "Order placed, secure file link issued to partner." },
      { status: "in_review", at: "2026-07-09", note: "DFM check passed with 2 minor notes." },
      { status: "in_production", at: "2026-07-10", note: "Panelization complete, boards in fabrication." },
    ],
  },
];

export const seedDisputes: Dispute[] = [
  {
    id: "ds_9001",
    productTitle: "RP2350 Multi-function Pocket Instrument",
    buyerName: "Jordan Lee",
    sellerName: "SuLab",
    type: "missing_files",
    status: "seller_response",
    openedAt: "2026-07-11",
    messages: [
      { from: "buyer", at: "2026-07-11 09:12", body: "The STEP enclosure file referenced in the docs isn't in my download." },
      { from: "seller", at: "2026-07-11 14:40", body: "Apologies — the STEP was in a sub-folder that got excluded. Uploading a corrected v1.2.1 now." },
    ],
  },
];

export const seedIpComplaints: IpComplaint[] = [
  {
    id: "ip_7001",
    productTitle: "Generic USB-PD Trigger Board",
    complainant: "Acme Power Ltd.",
    rightsHolder: "Acme Power Ltd.",
    basis: "Alleged copy of a registered board layout.",
    status: "under_review",
    filedAt: "2026-07-06",
  },
];

export const seedEntitlements: Entitlement[] = [
  {
    id: "ent_3001",
    productId: "dp_rflib",
    productTitle: "High-quality RF Symbols & Footprints Pack",
    licenseName: "Standard License",
    grantedAt: "2026-06-20",
    downloadLimit: 10,
    downloadCount: 2,
    version: "2026.06",
    status: "active",
  },
];

export function getProduct(slug: string) {
  return products.find((p) => p.slug === slug);
}
