import { NextRequest } from "next/server";
import { labelPdf } from "@/lib/shippo-server";

/** Mock-mode label endpoint: a real, printable 4x6 PDF. With a live Shippo
 *  key this route is never used — label_url points at Shippo's CDN. */
export async function GET(req: NextRequest) {
  const sp = req.nextUrl.searchParams;
  const tn = sp.get("tn") ?? "0000";
  const provider = sp.get("provider") ?? "USPS";
  const ref = sp.get("ref") ?? "";
  const pdf = labelPdf([
    "TINDIE  x  SHIPPO  (test label)",
    "--------------------------------",
    `CARRIER   ${provider}`,
    `TRACKING  ${tn}`,
    ref ? `ORDER     ${ref}` : "",
    "",
    "FROM  SuLab / Tindie",
    "      2261 Market St",
    "      San Francisco CA 94114 US",
    "",
    "** NOT VALID FOR POSTAGE **",
    "Generated by the prototype's",
    "mock transaction endpoint.",
  ].filter(Boolean));
  return new Response(Buffer.from(pdf), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `inline; filename="label_${tn}.pdf"`,
    },
  });
}
